#!/usr/bin/env bash
# Displays 'Best School' in stdout 10 times unsing the while loop

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 9]
then
  echo "HI"
fi
echo "Best School"
(( index++ ))
done
